Feature/python code
germanFid/FieldAveraging pull request #11
Opened 2023-02-26 00:29 UTC by Lukedam

Коль мы переехали на питон, предлагаю объединить

2023-02-26 07:51 UTC, germanFid commented on averager.py
> +    return(ij_value)
1. Можно не ставить скобочки после ключевых слов вроде `if`, `elif`, `return`
Тут их надо убрать!

2023-02-26 07:56 UTC, germanFid requested changes
Также прошу впредь придерживаться этих конвенций наименования перменных:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/30950612/221398953-a797a98c-4845-4e99-a7ce-3313f0ad215e.png">

2023-02-26 07:56 UTC, germanFid commented on averager.py
> +    return(OutputField)
То же, что и в п.1

2023-02-26 07:56 UTC, germanFid commented on averager.py
>  def Test():
Перед объявлением функции должно стоять две пустых линии

2023-02-26 07:56 UTC, germanFid commented on averager.py
> +    AveragingWidth=1
Оператор и аргумент отделяются пробелами:
`AveragingWidth = 1`

Сделать это же в случаях ниже

2023-03-01 14:06 UTC, Lukedam commented
Причесал все по конвенции

2023-03-01 17:49 UTC, germanFid requested changes
`joined_lower` на то и `joined_lower`, что все маленькими буквами. Переделай, в общем ;)

2023-03-01 18:07 UTC, Lukedam commented
Аааааааргх

2023-03-02 18:33 UTC, germanFid approved these changes
Вот теперь нормально! Слава Богу, разобрался!

2023-03-06 14:41 UTC, merged